# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'vencalendar.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FechaAlta(object):
    def setupUi(self, FechaAlta):
        FechaAlta.setObjectName("FechaAlta")
        FechaAlta.resize(423, 298)
        self.dlgCalendar = QtWidgets.QWidget(FechaAlta)
        self.dlgCalendar.setObjectName("dlgCalendar")
        self.Calendar = QtWidgets.QCalendarWidget(self.dlgCalendar)
        self.Calendar.setGeometry(QtCore.QRect(0, 0, 421, 261))
        self.Calendar.setObjectName("Calendar")
        FechaAlta.setCentralWidget(self.dlgCalendar)
        self.menubar = QtWidgets.QMenuBar(FechaAlta)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 423, 21))
        self.menubar.setObjectName("menubar")
        FechaAlta.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(FechaAlta)
        self.statusbar.setObjectName("statusbar")
        FechaAlta.setStatusBar(self.statusbar)

        self.retranslateUi(FechaAlta)
        QtCore.QMetaObject.connectSlotsByName(FechaAlta)

    def retranslateUi(self, FechaAlta):
        _translate = QtCore.QCoreApplication.translate
        FechaAlta.setWindowTitle(_translate("FechaAlta", "MainWindow"))
