# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'vensalir.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_venSalir(object):
    def setupUi(self, venSalir):
        venSalir.setObjectName("venSalir")
        venSalir.resize(402, 207)
        self.btnBoxSalir = QtWidgets.QDialogButtonBox(venSalir)
        self.btnBoxSalir.setGeometry(QtCore.QRect(200, 120, 161, 32))
        self.btnBoxSalir.setOrientation(QtCore.Qt.Horizontal)
        self.btnBoxSalir.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.No|QtWidgets.QDialogButtonBox.Yes)
        self.btnBoxSalir.setObjectName("btnBoxSalir")
        self.lblMenSalir = QtWidgets.QLabel(venSalir)
        self.lblMenSalir.setGeometry(QtCore.QRect(10, 60, 381, 41))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lblMenSalir.setFont(font)
        self.lblMenSalir.setAlignment(QtCore.Qt.AlignCenter)
        self.lblMenSalir.setObjectName("lblMenSalir")
        self.lblImgAviso = QtWidgets.QLabel(venSalir)
        self.lblImgAviso.setGeometry(QtCore.QRect(40, 10, 41, 51))
        self.lblImgAviso.setText("")
        self.lblImgAviso.setPixmap(QtGui.QPixmap(":/avisosalir/iconoAviso.png"))
        self.lblImgAviso.setObjectName("lblImgAviso")

        self.retranslateUi(venSalir)
        self.btnBoxSalir.accepted.connect(venSalir.accept)
        self.btnBoxSalir.rejected.connect(venSalir.reject)
        QtCore.QMetaObject.connectSlotsByName(venSalir)

    def retranslateUi(self, venSalir):
        _translate = QtCore.QCoreApplication.translate
        venSalir.setWindowTitle(_translate("venSalir", "Desea salir?"))
        self.lblMenSalir.setText(_translate("venSalir", "¿Está seguro que desea salir de la aplicación?"))
import avisosalir_rc
